// This snippet file was generated by processing the source file:
// ./auth-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_state_listener_modular]
import { getAuth, onAuthStateChanged } from "firebase/auth";
import app from "./firebaseConfig";

const auth = getAuth(app);

export default stateListener = onAuthStateChanged(auth, (user) => {
  if (user) {
    console.log("signed in");
    // User is signed in, see docs for a list of available properties
    // https://firebase.google.com/docs/reference/js/firebase.User
    const uid = user.uid;
    console.log(uid);
    // ...
  } else {
    // User is signed out
    // ...
  }
});
// [END auth_state_listener_modular]
